NUM_ROUNDS = 100
TOPOLOGY_FILE = "topo.yml"
NUM_CLIENTS = 4

MODEL = "lenet_cifar10"  # vgg, lenet_mnist, lenet_cifar10
DATASET = "cifar10"  # mnist, cifar10

BATCH_SIZE = 32
PARTITIONER = "iid"  # "iid" or "dirichlet"
DIRICHLET_ALPHA = 0.5

TRAINING_LEARNING_RATE = 5 * 1e-4
TRAINING_WEIGHT_DECAY = 1e-4

TRAINING_SCHEDULER_STEP_SIZE = 10
TRAINING_SCHEDULER_GAMMA = 0.1
