NUM_ROUNDS = 250
TOPOLOGY_FILE = "topo-8clients.yml"

MODEL = "lenet"  # vgg, lenet

NUM_CLIENTS = 16
BATCH_SIZE = 32
PARTITIONER = "iid"  # "iid" or "dirichlet"
DIRICHLET_ALPHA = 0.5

TRAINING_LEARNING_RATE = 20 * 1e-4
TRAINING_WEIGHT_DECAY = 1e-4

TRAINING_SCHEDULER_STEP_SIZE = 10
TRAINING_SCHEDULER_GAMMA = 0.1
